services:
  mysql:
    image: mysql:8.4
    container_name: smart-clinic-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cms
    ports:
      - "3307:3306"
    volumes:
      - smart-clinic-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  mongodb:
    image: mongo:7
    container_name: smart-clinic-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - smart-clinic-mongodb-data:/data/db

volumes:
  smart-clinic-mysql-data:
  smart-clinic-mongodb-data:
